version: '3.8'

services:
  seal:
    build: .
    container_name: seal-yoruba
    runtime: nvidia  # For GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "8000:8000"    # Main server
      - "8080:8080"    # Jupyter
      - "8265:8265"    # Ray dashboard
      - "11111:11111"  # TTT server
      - "11112:11112"  # Query server
    volumes:
      - .:/workspace
      - ./data:/workspace/data
      - ./results:/workspace/results
      - ./knowledge-incorporation/data:/workspace/knowledge-incorporation/data
      - ./knowledge-incorporation/results:/workspace/knowledge-incorporation/results
    working_dir: /workspace
    command: bash
    stdin_open: true
    tty: true
    shm_size: '8gb'  # Increase shared memory for PyTorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Optional: Jupyter service
  jupyter:
    build: .
    container_name: seal-jupyter
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  default:
    driver: bridge 